name: untitled
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
#  my_local_package:
#    path: ./my_local_package
  flutter:
    sdk: flutter
#  animations:
#    git:
#      url: https://github.com/flutter/packages.git
#      ref: master
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true




